export type {
  ApiClickClaimNotificationBody,
  ApiCreateAddressBody,
  ApiCreateAddressResponse,
  ApiCreateClaimBody,
  ApiCreateClaimResponse,
  ApiCreatePhotoBody,
  ApiCreatePhotoResponse,
  ApiDeleteAddressBody,
  ApiDeleteAddressResponse,
  ApiDeletePhotoBody,
  ApiDeletePhotoResponse,
  ApiDeletePhotosBody,
  ApiDeletePhotosResponse,
  ApiEditUserPhotoBody,
  ApiEditUserPhotoResponse,
  ApiGetAddressBody,
  ApiGetAddressResponse,
  ApiGetAllAddressBody,
  ApiGetAllAddressResponse,
  ApiGetClaimantsBody,
  ApiGetClaimantsResponse,
  ApiGetClaimBody,
  ApiGetClaimResponse,
  ApiGetClaimsBody,
  ApiGetClaimsByEmailBody,
  ApiGetClaimsByEmailResponse,
  ApiGetClaimsByKeywordBody,
  ApiGetClaimsByKeywordResponse,
  ApiGetClaimsNotificationsBody,
  ApiGetClaimsNotificationsResponse,
  ApiGetClaimsResponse,
  ApiGetContractsBody,
  ApiGetContractsResponse,
  ApiGetRelatedClaimsBody,
  ApiGetRelatedClaimsResponse,
  ApiLogInBody,
  ApiLogInResponse,
  ApiSignUpBody,
  ApiSignUpResponse,
  ApiUpdateAddressBody,
  ApiUpdateAddressResponse,
  ApiUpdateClaimBody,
  ApiUpdateClaimResponse,
  ApiDeleteClaimBody,
  ApiDeleteClaimResponse,
  ApiUpdateUserBody,
  ApiUpdateUserResponse,
} from './api';

export type { ICON } from './icon';

// 이미지 종류
export type PhotoKinds = 'claim' | 'remove';
